app/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(15))
    notes = db.relationship('Note')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager


db = SQLAlchemy()
DB_NAME = 'database.db'


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'

    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.login_message_category = 'info'
    login_manager.login_message = ''
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app


def create_database(app):
    if not path.exists('app/' + DB_NAME):
        db.create_all(app=app)
        print('Database was created!')

app/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
import functools

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    else:
        if request.method == 'POST':
            email = request.form.get('email')
            password = request.form.get('password')

            user = User.query.filter_by(email=email).first()
            if user:
                if check_password_hash(user.password, password):
                    login_user(user, remember=True)
                    return redirect(url_for('views.home'))
                else:
                    flash('Incorrect password', category='error')
            else:
                flash('Email does not exist.', category='error')

        return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    else:
        if request.method == 'POST':
            email = request.form.get('email')
            first_name = request.form.get('firstName')
            password1 = request.form.get('password1')
            password2 = request.form.get('password2')

            user = User.query.filter_by(email=email).first()
            if user:
                flash('Email already exists.', category='error')
            elif len(email) < 4:
                flash('Email must be greater than 3 characters.', category='error')
            elif len(first_name) < 2:
                flash('First name must be greater than 1 characters.', category='error')
            elif password1 != password2:
                flash('Password doesn\'t match.', category='error')
            elif len(password1) < 7:
                flash('Password must be at least 7 characters.', category='error')
            else:
                new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
                db.session.add(new_user)
                db.session.commit()

                flash('Account created!', category='success')
                return redirect(url_for('views.home'))

        return render_template('sign_up.html', user=current_user)

app/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from .models import Note
from . import db
from .helper import csv_df_to_html, make_facies_log_plot, predict, combine_result
import json
import os
from keras.models import load_model


views = Blueprint('views', __name__)
APP_ROOT = os.path.dirname(os.path.abspath(__file__))
UPLOAD_FOLDER = os.path.join(APP_ROOT, 'uploads')
ALLOWED_EXTENSIONS = {'csv'}
model = load_model(os.path.join(APP_ROOT, 'static/model.h5'))


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@views.route('/about')
def about():
    return render_template('about.html', user=current_user)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file was uploaded!', category='error')
            return redirect(request.url)

        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected files', category='error')
            return redirect(request.url)

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file_path = os.path.join(UPLOAD_FOLDER, filename)
            file.save(file_path)
            flash('File was uploaded!', category='success')

            tables = csv_df_to_html(file=file_path, describe=False)
            describe_tables = csv_df_to_html(file=file_path, describe=True)

            # visualize
            logs_img = make_facies_log_plot(file_path)

            # prediction
            predict_cols = predict(file_path, model)
            # combine result in one DataFrame
            result_table = combine_result(file_path, predict_cols)
            result_table = result_table.to_html()

            return render_template('visual.html', user=current_user, tables=[tables], describe_tables=[describe_tables], logs_img=logs_img, predicted_table=[result_table])

    return render_template('home.html', user=current_user)


@views.route('delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    note_id = note['noteId']
    note = Note.query.get(note_id)

    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()


    return jsonify({})

app/templates/about.html
{% extends 'base.html' %}
{% block title %} About {% endblock %}
{% block content %}
    <div class="row my-5">
        <div class="col">
            <h3 class="h3 text-center">About this App</h3>
        </div>
    </div>

    <div class="row my-3">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="h5 text-center">
                                Latar Belakang
                            </h5>
                        </div>
                        <div class="card-body">
                            <p class="text-justify">
                                Data well log merupakan data yang diperoleh dari sumur bor eksplorasi yang berupa data
                                dari sifat petrofisika seperti gama , resistivitas, porositas dan lainnya. Analisis
                                dengan menggunakan data well log ini sering digunakan dalam industry perminyakan atau
                                pertambangan, untuk mengetahui lapisan atau facies dan strukturnya berdasarkan sifat
                                petrofisika yang diamati. Namun pada umumnya Analisa data well log masih dilakukan
                                secara manual sehingga kemungkinan membutuhkan waktu yang lama serta perlu banyak ahli
                                yang melakukakannya.
                            </p>
                            <img src="{{ url_for('static', filename='well_latarbelakang.png') }}" alt="Well Logs"
                                 class="img-responsive d-block mx-auto">
                            <p class="text-justify">
                                Berdasarkan latar belakang yang telah disampaikan, kami tergerak untuk membuap suatu
                                aplikasi yang dapat mendeteksi fasies atau lapisan dari data well log yang telah
                                diberikan, aplikasi ini nantinya akan menjadi suatu alat yang dapat digunakan oleh
                                seorang geofisikawan dalam menganalisis data well log, dan harapanya dengan aplikasi ini
                                analisis yang dilakukan menjadi lebih cepat , akurat dan murah.
                            </p>
                        </div>
                    </div>
                    <br/>
                    <div class="card">
                        <div class="card-header">
                            <h5 class="h5 text-center">
                                Tim Pengembang
                            </h5>
                        </div>
                        <div class="card-body">
                            <p class="text-justify">
                                Dosen Pembimbing: Dr. Indra Gunawan, S.Kom., M.Si.
                            </p>
                            <p class="text-justify">
                                Anggota Tim:
                            <ul>
                                <li>Andriana A</li>
                                <li>Ibnu Nahwitama</li>
                                <li>Muhammad Iqbal Khatami</li>
                                <li>Nur Sabilly</li>
                                <li>Wahana Alfin Shihab</li>
                            </ul>
                            </p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/base.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <meta charset="utf-8"/>#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1"/>#}
{#    <link#}
{#            rel="stylesheet"#}
{#            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"#}
{#            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"#}
{#            crossorigin="anonymous"#}
{#    />#}
{#    <link#}
{#            rel="stylesheet"#}
{#            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"#}
{#            crossorigin="anonymous"#}
{#    />#}
{##}
{#    <title>{% block title %}Home{% endblock %}</title>#}
{#</head>#}
{#<body>#}
{#<nav class="navbar navbar-expand-lg navbar-dark bg-dark">#}
{#    <button#}
{#            class="navbar-toggler"#}
{#            type="button"#}
{#            data-toggle="collapse"#}
{#            data-target="#navbar"#}
{#    >#}
{#        <span class="navbar-toggler-icon"></span>#}
{#    </button>#}
{#    <div class="collapse navbar-collapse" id="navbar">#}
{#        <div class="navbar-nav">#}
{#            {% if user.is_authenticated %}#}
{#                <a class="nav-item nav-link" id="home" href="/">Home</a>#}
{#                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>#}
{#            {% else %}#}
{#                <a class="nav-item nav-link" id="login" href="/login">Login</a>#}
{#                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{#</nav>#}
{##}
{#{% with messages = get_flashed_messages(with_categories=true) %}#}
{#    {% if messages %}#}
{#        {% for category, message in messages %}#}
{#            {% if category == 'error' %}#}
{#                <div class="alert alert-danger alert-dismissable fade show" role="alert">#}
{#                    {{ message }}#}
{#                    <button type="button" class="close" data-dismiss="alert">#}
{#                        <span aria-hidden="true">&times;</span>#}
{#                    </button>#}
{#                </div>#}
{#            {% else %}#}
{#                <div class="alert alert-success alert-dismissable fade show" role="alert">#}
{#                    {{ message }}#}
{#                    <button type="button" class="close" data-dismiss="alert">#}
{#                        <span aria-hidden="true">&times;</span>#}
{#                    </button>#}
{#                </div>#}
{#            {% endif %} {% endfor %} {% endif %} {% endwith %}#}
{##}
{#<div class="container">{% block content %} {% endblock %}</div>#}
{#<script#}
{#        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"#}
{#        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"#}
{#        crossorigin="anonymous"#}
{#></script>#}
{#<script#}
{#        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"#}
{#        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"#}
{#        crossorigin="anonymous"#}
{#></script>#}
{#<script#}
{#        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"#}
{#        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"#}
{#        crossorigin="anonymous"#}
{#></script>#}
{##}
{#<script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"#}
{#></script>#}
{#</body>#}
{#</html>#}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Well Logs">
    <meta name="author" content="Nur Sabilly">

    <title>{% block title %} {% endblock %} - Well Logs</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" src="{{ url_for('static', filename='style.css') }}">
</head>

<body>

{#nav#}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Well Logs Apps</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{{ url_for('views.home') }}">Home</a>
            <a class="p-2 text-dark" href="{{ url_for('views.about') }}">About</a>
            <a class="p-2 text-dark" href="{{ url_for('auth.logout') }}">Logout</a>
        {% else %}
            <a class="p-2 text-dark" href="{{ url_for('views.about') }}">About</a>
            <a class="p-2 text-dark" href="{{ url_for('auth.login') }}">Login</a>
            <a class="p-2 text-dark" href="{{ url_for('auth.sign_up') }}">Register</a>
        {% endif %}
    </nav>
    {#      <a class="btn btn-outline-primary" href="#">Sign up</a>#}
</div>

{# content #}
<div class="container content">
    {% block content %}
    {% endblock %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="text-center text-secondary">Made by Group 3. Technopreneur Geoscience Class Kampus Merdeka ITB</p>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/home.html
{% extends 'base.html' %}
{% block title %} Dashboard {% endblock %}
{% block content %}
    <div class="row my-5">
        <div class="col">
            <h3 class="h3 text-center">Well logs apps</h3>
        </div>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="row">
                    <div class="col">
                        {% if category == 'error' %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Sorry,</strong> {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% else %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row my-3">
        <div class="col">
            <div class="card">
                <div class="card-header text-center">
                    Main Features
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <div class="card">
                                <div class="card-header text-center">
                                    <b>Smart Well Logs</b>
                                </div>
                                <div class="card-body">
                                    <p class="text-center">Takes a well logs file in CSV and see our apps visualizes it
                                        well!</p>
                                    <div class="input-group mb-3">
                                        <form class="form-control" method="POST" enctype=multipart/form-data>
                                            <input type="file" accept=".csv" name="file" class="custom-file-input" id="file" required>
                                            <label class="custom-file-label" for="file">Choose a CSV file</label>
                                            <button type="submit" class="btn btn-block btn-primary">Visualize</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}
{% block content %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="row">
                    <div class="col">
                        {% if category == 'error' %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Sorry,</strong> {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% else %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row my-2">
        <div class="col-sm-2 col-md-4"></div>
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="h3 text-center">Login</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control" id="email"
                                   placeholder="Enter your email" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" class="form-control" id="password"
                                   placeholder="Password" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-2 col-md-4"></div>
    </div>
{% endblock %}

app/templates/sign_up.html
{% extends 'base.html' %}
{% block title %} Register {% endblock %}
{% block content %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="row">
                    <div class="col">
                        {% if category == 'error' %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Sorry,</strong> {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% else %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                <strong>Successful!</strong> {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row my-2">
        <div class="col-sm-2 col-md-4"></div>
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="h3 text-center">Register</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group">
                            <label for="firstName">Full Name</label>
                            <input type="text" name="firstName" class="form-control" id="firstName"
                                   placeholder="Enter your name" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control" id="email"
                                   placeholder="Enter your email" required>
                        </div>
                        <div class="form-group">
                            <label for="password1">Password</label>
                            <input type="password" name="password1" class="form-control" id="password1"
                                   placeholder="Password" required>
                        </div>
                        <div class="form-group">
                            <label for="password2">Password Confirmation</label>
                            <input type="password" name="password2" class="form-control" id="password2"
                                   placeholder="Password" required>
                        </div>
                        <button type="submit" class="btn btn-warning btn-block">Register</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-2 col-md-4"></div>
    </div>
{% endblock %}

app/templates/visual.html
{% extends 'base.html' %}
{% block title %} Visualization Result {% endblock %}
{% block content %}
    <div class="row my-5">
        <div class="col">
            <h3 class="h3 text-center">Visualization Result</h3>
        </div>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="row">
                    <div class="col">
                        {% if category == 'error' %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Sorry,</strong> {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% else %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row my-3">
        <div class="col">
            <div class="card">
                <div class="card-header text-center">
                    <h4 class="h4">Result</h4>
                </div>
                <div class="card-body">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="h5 text-center">Logs Plot</h5>
                        </div>
                        <div class="body table text-center mx-0">
                            <br/>
                            {{ logs_img|safe }}
                        </div>
                    </div>
                    <br/>
                    <div class="card">
                        <div class="card-header">
                            <h5 class="h5 text-center">Tabular Representation</h5>
                        </div>
                        <div class="body table text-center mx-0">
                            <br/>
                            {% for table in tables %}
                                {{ table|safe }}
                            {% endfor %}
                        </div>
                    </div>
                    <br/>
                    <div class="card">
                        <div class="card-header">
                            <h5 class="h5 text-center">Statistical Description</h5>
                        </div>
                        <div class="body table text-center mx-0">
                            <br/>
                            {% for table in describe_tables %}
                                {{ table|safe }}
                            {% endfor %}
                        </div>
                    </div>
                <br/>
                <div class="card">
                        <div class="card-header">
                            <h5 class="h5 text-center">Prediction</h5>
                        </div>
                        <div class="body table text-center mx-0">
                            <br/>
                            {% for table in predicted_table %}
                                {{ table|safe }}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}